// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouypqcymrckqhqpnjhqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91eXBxY3ltcmNrcWhxcG5qaHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTkyMzMsImV4cCI6MjA2MDQ5NTIzM30.mpjet2eZIIJyVImEbAE1yVcpNFyQ3YCU7OK8FdbBNKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);